## Reference:

https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py

https://www.tensorflow.org/versions/master/api_docs/python/tf/matmul

In [1]:
from keras import backend as K
K.set_image_data_format('channels_last')

from keras.utils import to_categorical
import numpy as np

import tensorflow as tf
from keras import initializers, layers

Using TensorFlow backend.


## K.expand_dims

In [2]:
v_1 = K.random_normal_variable(shape=(2, 3), mean=0, scale=1)
print(v_1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>


In [5]:
print("K.eval: \n",K.eval(v_1))
print("K.get_value should be the same as K.eval: \n", K.get_value(v_1))

K.eval: 
 [[ 1.18456972  0.50871342  2.24240661]
 [ 0.63519263 -1.73597264  1.11316562]]
K.get_value should be the same as K.eval: 
 [[ 1.18456972  0.50871342  2.24240661]
 [ 0.63519263 -1.73597264  1.11316562]]


In [10]:
v_1_expand = K.expand_dims(v_1, axis=0)
print("expand dims at 0, shape becomes to: ", v_1_expand.get_shape())
print("expand dims at 0: \n", K.get_value(v_1_expand))

expand dims at 0, shape becomes to:  (1, 2, 3)
expand dims at 0: 
 [[[ 1.18456972  0.50871342  2.24240661]
  [ 0.63519263 -1.73597264  1.11316562]]]


In [9]:
v_1_expand2 = K.expand_dims(v_1, axis=1)
print("expand dims at 1, shape becomes to: ", v_1_expand2.get_shape())
print("expand dims at 1: \n", K.eval(v_1_expand2))

expand dims at 1, shape becomes to:  (2, 1, 3)
expand dims at 1: 
 [[[ 1.18456972  0.50871342  2.24240661]]

 [[ 0.63519263 -1.73597264  1.11316562]]]


In [11]:
v_1_expand3 = K.expand_dims(v_1, axis=2)
print("expand dims at 2, shape becomes to: ", v_1_expand3.get_shape())
print("expand dims at 2: \n", K.eval(v_1_expand3))

expand dims at 2, shape becomes to:  (2, 3, 1)
expand dims at 2: 
 [[[ 1.18456972]
  [ 0.50871342]
  [ 2.24240661]]

 [[ 0.63519263]
  [-1.73597264]
  [ 1.11316562]]]


## K.batch_dot

In [21]:
v_2 = K.variable(value = np.array([[1, 2], [3, 4]]), dtype='float64')
print("shape of v_2: ", v_2.get_shape())
print("K shape of v2: ", K.shape(v_2))

shape of v_2:  (2, 2)
K shape of v2:  Tensor("Shape_3:0", shape=(2,), dtype=int32)


In [19]:
print("ndim of v2: ", K.ndim(v_2))

ndim of v2:  2


In [20]:
v_3 = K.ones(shape=(32, 20))
print(v_3)

<tf.Variable 'Variable_4:0' shape=(32, 20) dtype=float32_ref>


In [26]:
shape_1 = tf.concat([K.shape(v_3), [1] * 1], axis=0)
print(shape_1)
print("get_shape: ", shape_1.get_shape())
print("value of shape: ", K.get_value(shape_1))

Tensor("concat_3:0", shape=(3,), dtype=int32)
get_shape:  (3,)
value of shape:  [32 20  1]


In [27]:
v_3_reshape = tf.reshape(v_3, shape_1)
print("v3's new shape: ", v_3_reshape.get_shape())

v3's new shape:  (32, 20, 1)


In [29]:
v4 = K.ones(shape=(32, 30, 20))
print("v4 shape: ", v4.get_shape())

v4 shape:  (32, 30, 20)


In [36]:
v6 = K.batch_dot(v_3_reshape, v4, axes=[1, 2])
print("shape of v6: ", K.int_shape(v6))

shape of v6:  (32, 1, 30)


## K.tile

In [38]:
v7 = K.variable(np.array([[1, 2]]), dtype='float64')
print("shape of v7: ", v7.get_shape())

shape of v7:  (1, 2)


In [42]:
v8 = K.tile(v7, [3, 1])
print("shape of v8: ", v8.get_shape())
print("v8: \n", K.get_value(v8))

shape of v8:  (3, 2)
v8: 
 [[ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]]


In [43]:
v9 = K.tile(v7, [3, 4])
print("shape of v9: ", v9.get_shape())
print("v9: \n", K.get_value(v9))

shape of v9:  (3, 8)
v9: 
 [[ 1.  2.  1.  2.  1.  2.  1.  2.]
 [ 1.  2.  1.  2.  1.  2.  1.  2.]
 [ 1.  2.  1.  2.  1.  2.  1.  2.]]
